# Site
title:              天秤座不会取名字
bio:                'UNDER CONSTRUCTION'
description:        ''
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
#url:                https://zhaotw.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   zhaotw

# Social
google:
  #plus:            #username
  analytics:        UA-151214092-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              zhao_tw@outlook.com
twitter:            zhao_tw
#facebook:           profile.php?id=100009241821337
github-url:         zhaotw
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          zhao_tw
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              威天昭
#dribbble:          username
#youtube:           username
youtube-channel:    UCRD4hP7uN05MJ1t_1OlzNMg?view_as=subscriber
#soundcloud:        username
weibo:              5199726126/profile?topnav=1&wvr=6
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
